A0-3223: Add featurenet compatibility (#9)
* Add featurenet compatibility

diff --git a/create-featurenet/action.yml b/create-featurenet/action.yml
--- a/create-featurenet/action.yml
+++ b/create-featurenet/action.yml
@@ -12,6 +12,9 @@ inputs:
   repo-featurenets-name:
     description: 'Name of the repository containing featurenets manifests'
     required: true
+  repo-featurenet-template-name:
+    description: 'Name of the repository containing featurenet template'
+    required: true
   argo-host:
     description: 'ArgoCD host'
     required: true
@@ -63,6 +66,10 @@ inputs:
     default: "false"
   hard-refresh:
     description: 'Make hard-refresh of ArgoCD application'
+    required: false
+    default: "false"
+  wait-for-finalized-heads:
+    description: 'Wait for heads finalization'
     required: false
     default: "false"
 outputs:
@@ -123,14 +130,6 @@ runs:
       id: get-ref-properties
       uses: Cardinal-Cryptography/github-actions/get-ref-properties@v1
 
-    - name: Checkout featurenets repo
-      uses: actions/checkout@v3
-      with:
-        repository: Cardinal-Cryptography/${{ inputs.repo-featurenets-name }}
-        token: ${{ inputs.gh-ci-token }}
-        path: "${{ inputs.repo-featurenets-name }}"
-        ref: main
-
     - name: Get node commit SHA
       if: ${{ inputs.featurenet-aleph-node-image == 'testnet' ||
         inputs.featurenet-aleph-node-image == 'mainnet' }}
@@ -139,12 +138,73 @@ runs:
       with:
         env: ${{ inputs.featurenet-aleph-node-image }}
 
+    - name: Checkout latest aleph-node repo to get featurenets tag
+      uses: actions/checkout@v3
+      with:
+        repository: Cardinal-Cryptography/aleph-node
+        token: ${{ inputs.gh-ci-token }}
+        path: "aleph-node-compatibility"
+        fetch-depth: 0
+        ref: main
+
+    - name: Checkout aleph-node commit repo to get featurenet template tag
+      shell: bash
+      run: |
+        cd aleph-node-compatibility
+        if [[ "${{ inputs.featurenet-aleph-node-image }}" != "" ]]; then
+          if [[ "${{ inputs.featurenet-aleph-node-image }}" == "testnet" \
+            || "${{ inputs.featurenet-aleph-node-image }}" == "mainnet" ]]; then
+            git checkout "${{ steps.get-node-commit-sha.outputs.sha }}"
+          else
+            git checkout "${{ inputs.featurenet-aleph-node-image }}"
+          fi
+        else
+          git checkout "${{ steps.get-ref-properties.outputs.branch }}"
+        fi
+
+    - name: Checkout featurenets repo
+      uses: actions/checkout@v3
+      with:
+        repository: Cardinal-Cryptography/${{ inputs.repo-featurenets-name }}
+        token: ${{ inputs.gh-ci-token }}
+        path: "${{ inputs.repo-featurenets-name }}"
+        ref: main
+
+    - name: Checkout featurenet template repo
+      uses: actions/checkout@v3
+      with:
+        repository: Cardinal-Cryptography/${{ inputs.repo-featurenet-template-name }}
+        token: ${{ inputs.gh-ci-token }}
+        path: "${{ inputs.repo-featurenet-template-name }}"
+        ref: compatibility
+        fetch-depth: 0
+
+    - name: Get compatible featurenet template version
+      id: get-featurenet-template-tag
+      shell: bash
+      # yamllint disable rule:line-length
+      run: |
+        cd "${{ inputs.repo-featurenet-template-name }}"
+        ./Compatibility.sh "${{ github.workspace }}/aleph-node-compatibility" | grep "__output:tag:" | cut -d: -f3 > tmp-output.txt
+        featurenet_template_tag=$(cat tmp-output.txt)
+        if [[ -z "${featurenet_template_tag}" ]]; then
+          echo "!!! Error in getting compatible featurenet template tag"
+          exit 1
+        fi
+        echo "featurenet-template-tag=${featurenet_template_tag}" >> $GITHUB_OUTPUT
+
+        echo "Checking out ${featurenet_template_tag}..."
+        git checkout "${featurenet_template_tag}"
+      # yamllint enable rule:line-length
+
     - name: Start featurenet from PR branch
       id: start-featurenet
       shell: bash
       # yamllint disable rule:line-length
+      env:
+        OPSSH_TARGETPATH: ${{ github.workspace }}/${{ inputs.repo-featurenets-name }}
       run: |
-        cd "${{ inputs.repo-featurenets-name }}"
+        cd "${{ inputs.repo-featurenet-template-name }}"
         # featurenet creation from commit from PR
         if [[ "${{ inputs.featurenet-aleph-node-image }}" == "" ]]; then
           pr_image_tag="fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo-with-sha }}"
@@ -165,7 +225,7 @@ runs:
           # Disabling hook here as work in progress
           fnet_create_hook="false"
         fi
-        ./Ops.sh create-featurenet-using-kustomize \
+        ./Ops.sh create-featurenet \
           "${{ inputs.featurenet-name }}" \
           "${fnet_aleph_node_image}" \
           "${fnet_bootstrap_chain_node_image}" \
@@ -181,11 +241,22 @@ runs:
     - name: Set featurenet expiration
       if: inputs.expiration != ''
       shell: bash
+      env:
+        OPSSH_TARGETPATH: ${{ github.workspace }}/${{ inputs.repo-featurenets-name }}
       run: |
-        cd "${{ inputs.repo-featurenets-name }}"
+        cd "${{ inputs.repo-featurenet-template-name }}"
         ./Ops.sh create-featurenet-expiration \
           "${{ inputs.featurenet-name }}" \
           "${{ inputs.expiration }}"
+
+    - name: Save template version
+      shell: bash
+      # yamllint disable rule:line-length
+      run: |
+        cd "${{ inputs.repo-featurenets-name }}"
+        echo "${{ steps.get-featurenet-template-tag.outputs.featurenet-template-tag }}" \
+          > fe-${{ inputs.featurenet-name }}.tag.txt
+      # yamllint enable rule:line-length
 
     - name: Commit featurenet change
       uses: EndBug/add-and-commit@v9.1.1
@@ -194,14 +265,25 @@ runs:
         author_email: "${{ inputs.git-commit-email }}"
         # yamllint disable-line rule:line-length
         message: "Upsert featurenet ${{ inputs.featurenet-name }} with image: ${{ inputs.featurenet-aleph-node-image != '' && inputs.featurenet-aleph-node-image || steps.get-ref-properties.outputs.branch-name-for-argo-with-sha }}"
-        add: '["*.yaml","*.expiration.txt"]'
+        add: '["*.yaml","*.expiration.txt","*.tag.txt"]'
         cwd: "${{ inputs.repo-featurenets-name }}"
 
     - name: Refresh Argo and wait for the creation to be finished
       shell: bash
+      env:
+        OPSSH_TARGETPATH: "${{ github.workspace }}/${{ inputs.repo-featurenets-name }}"
       run: |
         cd "${{ inputs.repo-featurenets-name }}"
         ./Ops.sh refresh-featurenets "${{ inputs.argo-host }}" \
           "${{ inputs.argo-sync-user-token }}" \
           "${{ inputs.featurenet-name }}" \
           "${{ inputs.hard-refresh == 'true' && 'true' || 'false' }}"
+
+    - name: Wait for the unique consecutive finalized heads
+      if: inputs.wait-for-finalized-heads == 'true'
+      shell: bash
+      env:
+        OPSSH_TARGETPATH: "${{ github.workspace }}/${{ inputs.repo-featurenets-name }}"
+      run: |
+        cd "${{ inputs.repo-featurenet-template-name }}"
+        ./Ops.sh wait-for-finalized-heads "${{ steps.start-featurenet.outputs.ws-hostname }}"
