Added validate inputs step

diff --git a/get-aleph-node-fqdn-image/action.yml b/get-aleph-node-fqdn-image/action.yml
--- a/get-aleph-node-fqdn-image/action.yml
+++ b/get-aleph-node-fqdn-image/action.yml
@@ -34,6 +34,26 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        if [[ ! '${{ inputs.ref }}' =~ ^[a-zA-Z0-9][a-zA-Z0-9\._\-]{1,48}$ ]]; then
+          echo "!!! Invalid ref"
+          exit 1
+        fi
+        if [[ '${{ inputs.test-binary != 'true' && inputs.test-binary != 'false' }}' ]]; then
+          echo "!!! test binary should be either true or false"
+        fi
+        if [[ -z '${{ inputs.ecr-dev-node-repo }}' ]]; then
+          echo "!!! ecr-dev-node-repo is empty"
+          exit 1
+        fi
+        if [[ -z '${{ inputs.ecr-prod-node-repo }}' ]]; then
+          echo "!!! ecr-prod-node-repo is empty"
+          exit 1
+        fi
+
+
     - name: Get Testnet or Mainnet node's commit SHA
       if: ${{ inputs.ref == 'mainnet' || inputs.ref == 'testnet' }}
       id: get-node-commit-sha-from-net
