Add checking inputs

diff --git a/download-contract-addresses/action.yml b/download-contract-addresses/action.yml
--- a/download-contract-addresses/action.yml
+++ b/download-contract-addresses/action.yml
@@ -34,6 +34,50 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check inputs
+      shell: bash
+      run: |
+        if [[
+          ! '${{ inputs.project }}' =~ ^[a-zA-Z0-9/_-]+$
+        ]]
+        then
+          echo '!!! Invalid project'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.chain-environment }}' =~ ^[a-zA-Z0-9/_-]+$
+        ]]
+        then
+          echo '!!! Invalid chain-environment'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.frontend-environment }}' =~ ^[a-zA-Z0-9/_-]+$
+        ]]
+        then
+          echo '!!! Invalid frontend-environment'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.s3-bucket }}' =~ ^[a-zA-Z0-9_-]+$
+        ]]
+        then
+          echo '!!! Invalid s3-bucket'
+          exit 1
+        fi
+
+        if [[
+          '${{ inputs.if-not-exist }}' != 'skip' && \
+          '${{ inputs.if-not-exist }}' != 'try' && \
+          '${{ inputs.if-not-exist }}' != 'fallback'
+        ]]; then
+          echo "!!! Invalid value for 'if-not-exist' argument, should be one of 'skip', 'try' or 'fallback'"
+          exit 1
+        fi
+
     - name: Download contract addresses from AWS S3 bucket
       uses: Cardinal-Cryptography/github-actions/get-file-from-s3@A0-4026-add-code-for-dealing-with-contracts
       env:
diff --git a/download-contract-artifact/action.yml b/download-contract-artifact/action.yml
--- a/download-contract-artifact/action.yml
+++ b/download-contract-artifact/action.yml
@@ -34,6 +34,50 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check inputs
+      shell: bash
+      run: |
+        if [[
+          ! '${{ inputs.project }}' =~ ^[a-zA-Z0-9/_-]+$
+        ]]
+        then
+          echo '!!! Invalid project'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.version }}' =~ ^[a-zA-Z0-9/_-\.]+$
+        ]]
+        then
+          echo '!!! Invalid version'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.contract }}' =~ ^[a-zA-Z0-9/_-]+$
+        ]]
+        then
+          echo '!!! Invalid contract'
+          exit 1
+        fi
+
+        if [[
+          ! '${{ inputs.s3-bucket }}' =~ ^[a-zA-Z0-9_-]+$
+        ]]
+        then
+          echo '!!! Invalid s3-bucket'
+          exit 1
+        fi
+
+        if [[
+          '${{ inputs.if-not-exist }}' != 'skip' && \
+          '${{ inputs.if-not-exist }}' != 'try' && \
+          '${{ inputs.if-not-exist }}' != 'fallback'
+        ]]; then
+          echo "!!! Invalid value for 'if-not-exist' argument, should be one of 'skip', 'try' or 'fallback'"
+          exit 1
+        fi
+
     - name: Download contract artifact from AWS S3 bucket
       uses: Cardinal-Cryptography/github-actions/get-file-from-s3@A0-4026-add-code-for-dealing-with-contracts
       env:
diff --git a/get-file-from-s3/action.yml b/get-file-from-s3/action.yml
--- a/get-file-from-s3/action.yml
+++ b/get-file-from-s3/action.yml
@@ -22,6 +22,23 @@ runs:
     - name: Copy file to AWS S3 bucket
       shell: bash
       run: |
+        if [[
+          ! '${{ inputs.s3-bucket-name }}' =~ ^[a-zA-Z0-9_-]+$
+        ]]
+        then
+          echo '!!! Invalid s3-bucket-name'
+          exit 1
+        fi
+
+        if [[
+          '${{ inputs.if-not-exist }}' != 'skip' && \
+          '${{ inputs.if-not-exist }}' != 'try' && \
+          '${{ inputs.if-not-exist }}' != 'fallback'
+        ]]; then
+          echo "!!! Invalid value for 'if-not-exist' argument, should be one of 'skip', 'try' or 'fallback'"
+          exit 1
+        fi
+
         aws s3api head-object \
           --bucket '${{ inputs.s3-bucket-name }}' \
           --key '${{ inputs.s3-bucket-path }}' \
