Add delete environment step

diff --git a/gh-deployments-environments/action.yaml b/gh-deployments-environments/action.yaml
--- a/gh-deployments-environments/action.yaml
+++ b/gh-deployments-environments/action.yaml
@@ -83,7 +83,7 @@ runs:
           exit 1
         fi
 
-        sleep 30
+        sleep 2
 
         curl -L \
           -H "Accept: application/vnd.github+json" \
@@ -108,3 +108,30 @@ runs:
           -H "X-GitHub-Api-Version: 2022-11-28" \
           -d '{"state":"${{ inputs.status }}"}' \
           https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/deployments/${{ inputs.deployment-id }}/statuses
+
+    - name: Delete environment
+      id: delete-environment
+      if: ${{ inputs.action == 'delete-environment' }}
+      shell: bash
+      run: |
+        if [[ "${{ inputs.env }}" == "devnet" || "${{ inputs.env }}" == "testnet" || "${{ inputs.env }}" == "mainnet" ]]; then
+          echo "!!! Invalid env"
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.env }}" ]]; then
+          echo "!!! env is empty"
+          exit 1
+        fi
+
+        curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ inputs.token }}"\
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/deployments?environment=${{ input.env }} > tmp-output.txt
+
+        cat tmp-output.txt
+
+        for deployment_id in $(cat tmp-output.txt | jq -r '.[].id'); do
+          echo "${deployment_id}"
+        done
