Add creating PR

diff --git a/test-upstream-merge/action.yml b/test-upstream-merge/action.yml
--- a/test-upstream-merge/action.yml
+++ b/test-upstream-merge/action.yml
@@ -15,6 +15,15 @@ inputs:
   upstream-branch:
     description: Upstream branch to merge from
     required: true
+  git-commit-author:
+    description: 'Git commit author when pushing to target repository'
+    required: true
+  git-commit-email:
+    description: 'Git commit email when pushing to target repository'
+    required: true
+  gh-ci-token:
+    description: 'GH token to be used in the action'
+    required: true
   slack-webhook-url:
     description: Slack webhook URL
     required: false
@@ -49,12 +58,36 @@ runs:
     - name: Merge upstream
       shell: bash
       id: merge-upstream
-      continue-on-error: true
       run: |
         cd target
-        git config user.name "AlephZero"
-        git config user.email "dummy.email@example.com"
+        git config user.name "${{ inputs.git-commit-author }}"
+        git config user.email "${{ inputs.git-commit-author }}"
+
+        pr_branch="upstreambot-merge-upstream"
+        git checkout -b "${pr_branch}"
+
+        set +e
+        merge_failed=0
         git merge upstream/${{ inputs.upstream-branch }}
+        if [[ $? != 0 ]]; then
+          merge_failed=1
+        fi
+
+        set -e
+        git add .
+        git commit -m "Merge upstream from ${{ inputs.upstream-repo-url }}@${{ inputs.upstream-branch }}"
+        git push origin "${{ inputs.pr_branch }}"
+
+        pr_body="Merging upstream from ${{ inputs.upstream-repo-url }}@{{ inputs.upstream-branch }}"
+        curl -L \
+          -X POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ inputs.gh-ci-token }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/${{ inputs.target-repo }}/pulls \
+          -d '{"title":"Merge upstream","body":"${{ pr_body }}","head":"${{ inputs.target-repo }}:${{ pr_branch }}","base":"${{ inputs.target-branch }}"}'
+
+        echo "merge-failed=${merge_failed}" >> $GITHUB_OUTPUT
 
     - name: Send notification
       shell: bash
@@ -63,7 +96,7 @@ runs:
         run_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         target="${{ inputs.target-repo }}/${{ inputs.target-branch }}"
         upstream="${{ inputs.upstream-repo-url }}@${{ inputs.upstream-branch }}"
-        if [[ "${{ steps.merge-upstream.outcome }}" == "failure" ]]; then
+        if [[ "${{ steps.merge-upstream.outputs.merge-failed }}" == "1" ]]; then
           cat ${{ github.action_path }}/slack-msg-failure.json > tmp-slack-msg.json
         else
           cat ${{ github.action_path }}/slack-msg-success.json > tmp-slack-msg.json
