Tidy up featurenet name variable

diff --git a/.github/workflows/_featurenet-create-from-net.yml b/.github/workflows/_featurenet-create-from-net.yml
--- a/.github/workflows/_featurenet-create-from-net.yml
+++ b/.github/workflows/_featurenet-create-from-net.yml
@@ -29,7 +29,25 @@ on:
         default: false
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
+    needs: [validate-inputs]
     name: Check vars and secrets
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
@@ -44,23 +62,6 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Get featurenet name
-        id: get-featurenet-name
-        shell: bash
-        # yamllint disable rule:line-length
-        run: |
-          if [[
-            "${{ inputs.featurenet-name }}" != "" && \
-            ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,30}$
-          ]]
-          then
-            echo "!!! Invalid name"
-            exit 1
-          fi
-          final_featurenet_name_local=${{ inputs.featurenet-name != '' && inputs.featurenet-name || github.run_id }}
-          echo "final-featurenet-name=$final_featurenet_name_local" >> $GITHUB_OUTPUT
-        # yamllint enable rule:line-length
-
       - name: Delete old featurenet app and data
         if: contains(github.event.pull_request.labels.*.name, 'state:created-featurenet')
         uses: Cardinal-Cryptography/github-actions/delete-featurenet@v2
@@ -74,7 +75,7 @@ jobs:
           repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: ${{ steps.get-featurenet-name.outputs.final-featurenet-name }}
+          featurenet-name: ${{ inputs.featurenet-name }}
           git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
           git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
@@ -84,7 +85,7 @@ jobs:
         with:
           step: start
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: ${{ steps.get-featurenet-name.outputs.final-featurenet-name }}
+          env: ${{ inputs.featurenet-name }}
           override: true
           debug: true
 
@@ -99,7 +100,7 @@ jobs:
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: ${{ steps.get-featurenet-name.outputs.final-featurenet-name }}
+          featurenet-name: ${{ inputs.featurenet-name }}
           featurenet-aleph-node-image: ${{ inputs.start == 'mainnet' && 'mainnet' || 'testnet' }}
           expiration: ${{ inputs.expiration }}
           replicas: ${{ inputs.replicas }}
@@ -115,7 +116,7 @@ jobs:
           step: finish
           token: ${{ secrets.CI_GH_TOKEN }}
           status: ${{ job.status }}
-          env: ${{ steps.get-featurenet-name.outputs.final-featurenet-name }}
+          env: ${{ inputs.featurenet-name }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
           # yamllint disable-line rule:line-length
           env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
diff --git a/.github/workflows/_featurenet-update.yml b/.github/workflows/_featurenet-update.yml
--- a/.github/workflows/_featurenet-update.yml
+++ b/.github/workflows/_featurenet-update.yml
@@ -31,8 +31,26 @@ on:
         type: boolean
         default: false
 
-jobs:
+jobs:  
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
+    needs: [validate-inputs]
     name: Check vars and secrets
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
