A0-3737: Support for dynamic sudo in FE bootstrap (#36)
* A0-3737: Support for dynamic sudo in FE bootstrap

diff --git a/.github/workflows/_featurenet-create.yml b/.github/workflows/_featurenet-create.yml
--- a/.github/workflows/_featurenet-create.yml
+++ b/.github/workflows/_featurenet-create.yml
@@ -40,6 +40,11 @@ on:
         required: false
         type: boolean
         default: false
+      sudo-account-id:
+        description: 'Sudo account ID'
+        type: string
+        required: false
+        default: '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY'
     outputs:
       ws-hostname:
         description: Hostname of the WS endpoint
@@ -61,6 +66,10 @@ jobs:
           fi
           if [[ ! '${{ inputs.aleph-node-image }}' =~ ^[a-z0-9][a-z0-9\._:/\-]{1,52}$ ]]; then
             echo "!!! Invalid aleph-node image"
+            exit 1
+          fi
+          if [[ ! '${{ inputs.sudo-account-id }}' =~ ^[a-zA-Z0-9]{48}$ ]]; then
+            echo "!!! Invalid sudo-account-id"
             exit 1
           fi
         # yamllint enable rule:line-length
@@ -123,6 +132,7 @@ jobs:
           git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
           git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
           wait-for-finalized-heads: "true"
+          sudo-account-id: ${{ inputs.sudo-account-id }}
 
       - name: Finish featurenet Deployment
         uses: bobheadxi/deployments@v1
diff --git a/create-featurenet/action.yml b/create-featurenet/action.yml
--- a/create-featurenet/action.yml
+++ b/create-featurenet/action.yml
@@ -55,6 +55,10 @@ inputs:
     description: 'Wait for heads finalization'
     required: false
     default: "false"
+  sudo-account-id:
+    description: 'Sudo account ID'
+    required: false
+    default: '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY'
 outputs:
   ws-hostname:
     description: Hostname of the WS endpoint
@@ -105,6 +109,10 @@ runs:
           echo "!!! Expected expiration to have values from set {3h, 12h, 24h, 48h, 96h, never}"
           exit 1
         fi
+        if [[ ! '${{ inputs.sudo-account-id }}' =~ ^[a-zA-Z0-9]{48}$ ]]; then
+          echo "!!! Invalid sudo-account-id"
+          exit 1
+        fi
 
     - name: Checkout featurenet template repo
       uses: actions/checkout@v3
@@ -132,6 +140,7 @@ runs:
           '${{ inputs.validators }}' \
           '${{ inputs.rolling-update-partition }}' \
           '${{ inputs.expiration }}' \
+          '${{ inputs.sudo-account-id }}' \
           ${{ inputs.internal == 'true' && '-i' || '' }} \
           -c -g | tee -a tmp-opssh-createfeaturenet-output.txt
 
