A0-4268: Support for chain-bootstrapper in actions

diff --git a/.github/workflows/_featurenet-create.yml b/.github/workflows/_featurenet-create.yml
--- a/.github/workflows/_featurenet-create.yml
+++ b/.github/workflows/_featurenet-create.yml
@@ -12,6 +12,10 @@ on:
         description: "FQDN of aleph-node image"
         required: true
         type: string
+      chain-bootstrapper-image:
+        description: "FQDN of chain-bootstrapper image"
+        required: true
+        type: string
       expiration:
         description: 'Time after which featurenet will be removed: "Xh" or "never"'
         required: false
@@ -66,6 +70,10 @@ jobs:
           fi
           if [[ ! '${{ inputs.aleph-node-image }}' =~ ^[a-z0-9][a-z0-9\._:/\-]{1,52}$ ]]; then
             echo "!!! Invalid aleph-node image"
+            exit 1
+          fi
+          if [[ ! '${{ inputs.chain-bootstrapper-image }}' =~ ^[a-z0-9][a-z0-9\._:/\-]{1,52}$ ]]; then
+            echo "!!! Invalid chain-bootstrapper image"
             exit 1
           fi
           if [[ ! '${{ inputs.sudo-account-id }}' =~ ^[a-zA-Z0-9]{48}$ ]]; then
@@ -125,6 +133,7 @@ jobs:
           repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
           featurenet-name: ${{ inputs.featurenet-name }}
           featurenet-aleph-node-image: ${{ inputs.aleph-node-image }}
+          featurenet-chain-bootstrapper-image: ${{ inputs.chain-bootstrapper-image }}
           expiration: ${{ inputs.expiration }}
           validators: ${{ inputs.validators }}
           internal: ${{ inputs.internal && 'true' || 'false' }}
diff --git a/create-featurenet/action.yml b/create-featurenet/action.yml
--- a/create-featurenet/action.yml
+++ b/create-featurenet/action.yml
@@ -31,6 +31,10 @@ inputs:
     description: 'aleph-node docker image tag'
     required: true
     default: ''
+  featurenet-chain-bootstrapper-image:
+    description: 'chain-bootstrapper docker image tag'
+    required: true
+    default: ''
   expiration:
     description: 'Time after which updatenet will be removed'
     required: false
@@ -82,6 +86,13 @@ runs:
         ]]
         then
           echo "!!! Invalid featurenet node image tag"
+          exit 1
+        fi
+        if [[
+          ! '${{ inputs.featurenet-chain-bootstrapper-image }}' =~ ^[a-z0-9][a-z0-9\._/:\-]{1,52}$
+        ]]
+        then
+          echo "!!! Invalid featurenet chain-bootstrapper image tag"
           exit 1
         fi
         if [[
@@ -141,6 +152,8 @@ runs:
           '${{ inputs.rolling-update-partition }}' \
           '${{ inputs.expiration }}' \
           '${{ inputs.sudo-account-id }}' \
+          'not-used' \
+          '${{ inputs.featurenet-chain-bootstrapper-image }}'
           ${{ inputs.internal == 'true' && '-i' || '' }} \
           -c -g | tee -a tmp-opssh-createfeaturenet-output.txt
 
