A0-3467: Refactor actions to match new template changes (#32)
* Refactor actions to match new template changes
---------

Co-authored-by: Marcin <marcin.radecki@cardinals.cc>

diff --git a/.github/workflows/_featurenet-create.yml b/.github/workflows/_featurenet-create.yml
--- a/.github/workflows/_featurenet-create.yml
+++ b/.github/workflows/_featurenet-create.yml
@@ -1,5 +1,5 @@
 ---
-name: FE - Create from net
+name: FE - Create
 
 on:
   workflow_call:
@@ -8,10 +8,15 @@ on:
         description: 'Name of the featurenet'
         required: true
         type: string
-      start:
-        description: 'aleph-node image to be started'
+      aleph-node-image:
+        description: "aleph-node image tag or 'mainnet' or 'testnet'"
         required: true
         type: string
+      featurenet-ecr-repo:
+        description: 'Use featurenets ECR repository instead of aleph-node'
+        required: false
+        type: boolean
+        default: false
       expiration:
         description: 'Time after which featurenet will be removed: "Xh" or "never"'
         required: false
@@ -27,6 +32,19 @@ on:
         required: false
         type: boolean
         default: false
+      rolling-update-partition:
+        description: |
+          Number from 0 to N-1, where N is size of am existing featurenet.
+          All aleph-node-validator-N with an ordinal N that is great than or equal to the partition
+          will be updated. If not specified, all nodes will be updated.
+        required: false
+        default: '0'
+        type: string
+      delete-first:
+        description: 'Delete featurenet before upserting'
+        required: false
+        type: boolean
+        default: false
 
 jobs:
   validate-inputs:
@@ -37,11 +55,13 @@ jobs:
         shell: bash
         # yamllint disable rule:line-length
         run: |
-          if [[
-          ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$
-          ]]
+          if [[ ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$ ]]
           then
             echo '!!! Invalid featurenet name'
+            exit 1
+          fi
+          if [[ ! '${{ inputs.aleph-node-image }}' =~ ^[a-z0-9][a-z0-9\._\-]{1,48}$ ]]; then
+            echo "!!! Invalid aleph-node image"
             exit 1
           fi
         # yamllint enable rule:line-length
@@ -63,18 +83,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Delete old featurenet app and data
-        if: contains(github.event.pull_request.labels.*.name, 'state:created-featurenet')
-        uses: Cardinal-Cryptography/github-actions/delete-featurenet@v4
+        if: ${{ inputs.delete-first == 'true' }}
+        uses: Cardinal-Cryptography/github-actions/delete-featurenet@v5
         with:
+          gh-ci-user: ${{ secrets.CI_GH_USER }}
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           aws-access-key-id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
-          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
-          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
-          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
-          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
           featurenet-name: ${{ inputs.featurenet-name }}
           git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
           git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
@@ -89,22 +106,29 @@ jobs:
           override: true
           debug: true
 
-      - name: Create featurenet from scratch, node binary from testnet or mainnet
-        uses: Cardinal-Cryptography/github-actions/create-featurenet@v4
+      - name: Get node commit SHA
+        if: ${{ inputs.aleph-node-image == 'mainnet' || inputs.aleph-node-image == 'testnet' }}
+        id: get-node-commit-sha
+        uses: Cardinal-Cryptography/github-actions/get-node-system-version@v1
+        with:
+          env: ${{ inputs.aleph-node-image }}
+
+      - name: Upsert featurenet with image tag
+        uses: Cardinal-Cryptography/github-actions/create-featurenet@v5
         id: create-featurenet
         with:
+          gh-ci-user: ${{ secrets.CI_GH_USER }}
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
-          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
-          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
-          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
-          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
           featurenet-name: ${{ inputs.featurenet-name }}
-          featurenet-aleph-node-image: ${{ inputs.start == 'mainnet' && 'mainnet' || 'testnet' }}
+          # yamllint disable-line rule:line-length
+          featurenet-aleph-node-image: ${{ (inputs.aleph-node-image == 'mainnet' || inputs.aleph-node-image == 'testnet') && steps.get-node-commit-sha.outputs.sha || inputs.aleph-node-image }}
+          featurenet-ecr-repo: ${{ inputs.featurenet-ecr-repo == true && 'true' || 'false' }}
           expiration: ${{ inputs.expiration }}
           replicas: ${{ inputs.replicas }}
           internal: ${{ inputs.internal && 'true' || 'false' }}
+          rolling-update-partition: ${{ inputs.rolling-update-partition }}
           git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
           git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
           wait-for-finalized-heads: "true"
